#
# Este compose é para construção e execução local do container
#
version: '3'

services:

  mule-esb:
#    image: vertigo/mule:3
    build:
      context: .
      dockerfile: Dockerfile-java
    ports:
      - 8081:8081 
    volumes:
      - ./src/main/domain:/opt/mule/domains/default
      - ./src/main/app:/opt/mule/apps/app
      - ./target/classes:/opt/mule/apps/app/classes
