#
# Este compose é para construção e execução local do container
#
version: '3'

services:

  mule-esb:
#    image: vertigo/mule
    build:
      context: .
      dockerfile: Dockerfile-java
    ports:
      - 8081:8081
    volumes:
      - ./target/hello-mule3-docker-1.0.0-SNAPSHOT.zip:/opt/mule/apps/hello.zip
    
