FROM openjdk:8u171-jdk

ENV MULE_HOME /opt/mule
ENV TZ America/Sao_Paulo

RUN mkdir -p /opt && \
    wget -q https://repository-master.mulesoft.org/nexus/content/repositories/releases/org/mule/distributions/mule-standalone/3.8.1/mule-standalone-3.8.1.tar.gz && \
    tar -xf mule-standalone-3.8.1.tar.gz && \
    mv mule-standalone-3.8.1 /opt && \
    mv /opt/mule-standalone-3.8.1 /opt/mule

#COPY --from=build /opt/hello.zip ${MULE_HOME}/apps

COPY ./target/hello-mule3-docker-1.0.0-SNAPSHOT.zip /opt/mule/apps/

# Define mount points.
VOLUME ["${MULE_HOME}/logs", "${MULE_HOME}/conf", "${MULE_HOME}/apps", "${MULE_HOME}/domains"]

# Define working directory.
WORKDIR ${MULE_HOME}

 #"hello" endpoint
EXPOSE 8081

HEALTHCHECK CMD curl --fail http://localhost:8081/hello || exit 1 

CMD /opt/mule/bin/mule
