#
# Este compose é para construção e execução local do container
#
version: '3'

services:

  mule-esb:
#    image: vertigo/mule
    build:
      context: .
#      dockerfile: Dockerfile-java
    ports:
      - 8081:8081
#    volumes:
#      - ./src/main/domain:/opt/mule/domains/mule-domain
#      - ./src/main/mule:/opt/mule/apps/app
#      - ./target/classes:/opt/mule/apps/app/classes
#      - ./mule-artifact.json:/opt/mule/apps/app/META-INF/mule-artifact/mule-artifact.json
#      - ./pom.xml:/opt/mule/pom.xml

